@startuml Packet

namespace Packet {
	abstract class AbstractPacket {
		+{static} pktMapping: Record<string, Class>;
		+{static} PKT_CONSTANT_NAME: string
		+serial: number
		+payload: any
		+{static} mapClass(name: string, value: Class): void
		+{static} getClass(name: string): Class
		+{static} isSensitive(clazz: Class): boolean
		+freeze(keys?: (keyof this)[]): this
	}

	namespace Client {
		abstract class ClientPacket extends .Packet.AbstractPacket {
			+validate(): boolean
			+extractHead(data: any): ClientPacket;
			+{abstract} extractPayload(): ClientPacket;
		}

		namespace Net {
			class CPlayerLoginPacket extends .Packet.Client.ClientPacket {}
			class CPlayerLogoutPacket extends .Packet.Client.ClientPacket {}
		}

		namespace Player {
			class CPlayerPacket extends .Packet.Client.ClientPacket {
				#identity: string
				#onlinePlayer: OnlinePlayer
				+extractHead(data: any): ClientPacket
				+validate(): boolean
				+getIdentity(): string
				-markOnlinePlayer(): void
			}

			class CPlayerChatPacket extends CPlayerPacket {
				#message: string
			}
		}
	}

	namespace Server {
		abstract class ServerPacket extends .Packet.AbstractPacket {}

		class SPlayerChatPacket extends ServerPacket {
			#message: string
		}
	}
}

@enduml
